base_path: "XXXXX"
image_x: "Pre"
image_y: "AP"
batch_size: 4
lr: 2.5e-5
n_epochs: 2000
start_epoch: 0
current_model: "XXX"
current_date: XXX
ckpt_model: None
ckpt_save_interval: 5
device: "cuda"
num_diff_step: 1000